### ISSUE TITLE
md2bbc.py bug

### ISSUE THREAD

**Issue by fireattack** [Trim21/personal-website#1]
1. `` `test` `` 会被转换成`[b]`而不是`[code]`

2. `[baidu](http://google.com)`会被转换成`[url=http://google.com]http://google.com[/url]` 而不是 `[url=http://google.com]baidu[/url]`

**Comment by Trim21** [comment]
第一点是因为bbcode没有inline code，`[code]test[/code]`也会变成独立的一行

第二个是bug。。。（
